# Generated by Django 4.0.4 on 2022-06-05 13:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0003_alter_act_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 13, 3, 55, 882936, tzinfo=utc), editable=False),
        ),
    ]
