# Generated by Django 4.0.4 on 2022-06-05 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0004_alter_act_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
